# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-15 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='article2tag',
            options={'verbose_name': '文章和标签的多对多关系表', 'verbose_name_plural': '文章和标签的多对多关系表'},
        ),
        migrations.AlterModelOptions(
            name='articledetail',
            options={'verbose_name': '文章详情', 'verbose_name_plural': '文章详情'},
        ),
        migrations.AlterModelOptions(
            name='articleupdown',
            options={'verbose_name': '点赞表', 'verbose_name_plural': '点赞表'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '博客信息', 'verbose_name_plural': '博客信息'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论表', 'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='avatar/default.png', upload_to='media/', verbose_name='头像'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('article', 'user')]),
        ),
    ]
